import StyleDictionary from 'style-dictionary';

/**
 * Custom CSS format that outputs :root (light) + .dark (dark) blocks.
 * Reads dark mode values from $extensions.dark.$value on semantic tokens.
 * Also outputs @keyframes from the spec.
 */
export function registerCssWithDarkFormat(sd: typeof StyleDictionary) {
  sd.registerFormat({
    name: 'css/oklch-with-dark',
    format: ({ dictionary }) => {
      const lightVars: string[] = [];
      const darkVars: string[] = [];

      dictionary.allTokens.forEach((token) => {
        const name = token.name;
        const value = token.value;
        const darkValue = token.$extensions?.dark?.$value
          ?? token.original?.$extensions?.dark?.$value;

        // Format CSS variable
        lightVars.push(`  --${name}: ${value};`);

        // If token has dark mode override, add to .dark block
        if (darkValue !== undefined) {
          // Resolve dark value — if it's a reference, SD should have resolved it
          // but $extensions values may not be auto-resolved, so we handle raw values
          darkVars.push(`  --${name}: ${darkValue};`);
        }
      });

      const keyframes = getKeyframes();

      return [
        '/**',
        ' * GENERATED FILE - DO NOT EDIT MANUALLY',
        ' * Generated by Style Dictionary from design tokens',
        " * Run 'pnpm build:tokens' to regenerate",
        ' */',
        '',
        ':root {',
        ...lightVars,
        '}',
        '',
        '.dark {',
        ...darkVars,
        '}',
        '',
        keyframes,
      ].join('\n');
    },
  });
}

function getKeyframes(): string {
  return `/* Keyframe Animations */

@keyframes fadeIn {
  from { opacity: 0; }
  to { opacity: 1; }
}

@keyframes fadeOut {
  from { opacity: 1; }
  to { opacity: 0; }
}

@keyframes slideUpIn {
  from { opacity: 0; transform: translateY(8px); }
  to { opacity: 1; transform: translateY(0); }
}

@keyframes slideDownIn {
  from { opacity: 0; transform: translateY(-8px); }
  to { opacity: 1; transform: translateY(0); }
}

@keyframes slideLeftIn {
  from { opacity: 0; transform: translateX(8px); }
  to { opacity: 1; transform: translateX(0); }
}

@keyframes slideRightIn {
  from { opacity: 0; transform: translateX(-8px); }
  to { opacity: 1; transform: translateX(0); }
}

@keyframes scaleIn {
  from { opacity: 0; transform: scale(0.95); }
  to { opacity: 1; transform: scale(1); }
}

@keyframes scaleOut {
  from { opacity: 1; transform: scale(1); }
  to { opacity: 0; transform: scale(0.95); }
}

@keyframes spin {
  to { transform: rotate(360deg); }
}

@keyframes pulse {
  50% { opacity: 0.5; }
}

@keyframes accordionDown {
  from { height: 0; opacity: 0; }
  to { height: var(--content-height); opacity: 1; }
}

@keyframes accordionUp {
  from { height: var(--content-height); opacity: 1; }
  to { height: 0; opacity: 0; }
}

@keyframes sheetSlideInRight {
  from { transform: translateX(100%); }
  to { transform: translateX(0); }
}

@keyframes sheetSlideInLeft {
  from { transform: translateX(-100%); }
  to { transform: translateX(0); }
}

@keyframes sheetSlideInTop {
  from { transform: translateY(-100%); }
  to { transform: translateY(0); }
}

@keyframes sheetSlideInBottom {
  from { transform: translateY(100%); }
  to { transform: translateY(0); }
}

@keyframes toastSlideIn {
  from { transform: translateX(calc(100% + 1rem)); }
  to { transform: translateX(0); }
}

@keyframes toastSwipeOut {
  from { transform: translateX(var(--toast-swipe-end-x)); }
  to { transform: translateX(calc(100% + 1rem)); }
}`;
}
