import StyleDictionary from 'style-dictionary';

export function registerDartFormat(sd: typeof StyleDictionary) {
  sd.registerFormat({
    name: 'dart/class',
    format: ({ dictionary, options }) => {
      const className = options?.className ?? 'AppTokens';

      const lines = dictionary.allTokens.map((token) => {
        const name = token.name;
        const type = token.$type;
        const value = token.value;

        if (type === 'color') {
          if (String(value).startsWith('0x')) {
            return `  static const Color ${name} = Color(${value});`;
          }
          if (value === 'transparent') {
            return `  static const Color ${name} = Colors.transparent;`;
          }
          return `  // ${name}: ${value} (non-hex color, apply manually)`;
        }

        if (type === 'dimension') {
          const num = parseFloat(String(value));
          if (!isNaN(num)) {
            return `  static const double ${name} = ${num};`;
          }
        }

        if (type === 'fontWeight') {
          const weight = parseInt(String(value), 10);
          if (!isNaN(weight)) {
            return `  static const FontWeight ${name} = FontWeight.w${weight};`;
          }
        }

        if (type === 'number') {
          const num = parseFloat(String(value));
          if (!isNaN(num)) {
            return `  static const double ${name} = ${num};`;
          }
        }

        if (type === 'fontFamily') {
          const primary = String(value).split(',')[0].trim().replace(/'/g, '');
          return `  static const String ${name} = '${primary}';`;
        }

        if (type === 'duration') {
          const ms = parseInt(String(value), 10);
          if (!isNaN(ms)) {
            return `  static const Duration ${name} = Duration(milliseconds: ${ms});`;
          }
        }

        return `  // ${name}: ${value} (type: ${type})`;
      });

      return [
        '// GENERATED FILE - DO NOT EDIT MANUALLY',
        '// Generated by Style Dictionary from design tokens',
        "// Run 'pnpm build:tokens' to regenerate",
        '',
        "import 'package:flutter/material.dart';",
        '',
        `class ${className} {`,
        `  ${className}._();`,
        '',
        ...lines,
        '}',
        '',
      ].join('\n');
    },
  });
}
